language: ruby
bundler_args: --without development
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
  - ree
  - rbx
  - jruby
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx
before_install:
  - gem install bundler
